apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: isc-in-cluster
spec:
  destination:
    namespace: isc
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/noam-codefresh/shared-gs
    path: resources
    directory:
      include: '{all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/production/*.yaml,runtimes/production/**/*.yaml,control-planes/*.yaml,control-planes/**/*.yaml,cf-prod.yaml}'
      recurse: true
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
